import string

class FormulaTemplate(string.Template):
    delimiter = '%'




SALES_METRES_WITH_FIRST_COLUMN = FormulaTemplate('=SUMIFS(%CRM_ROW:%CRM_ROW,$%CRM_PERIOD:$%CRM_PERIOD,$%SALES_PERIOD:$%SALES_PERIOD,$%CRM_TYPE:$%CRM_TYPE,"%DOC_TYPE")')
SALES_METRES_WITH_OTHER_COLUMN = FormulaTemplate('=SUMIFS(%CRM_ROW:%CRM_ROW,$%CRM_PERIOD:$%CRM_PERIOD,$%SALES_PERIOD:$%SALES_PERIOD,$%CRM_TYPE:$%CRM_TYPE,"%DOC_TYPE")+%PREV_COL:%PREV_COL')

CORRECTED_METRES = FormulaTemplate('=SUMIFS(%CRM_NAME!$BB:$BB,%CRM_NAME!$AM:$AM,$%SALES_PERIOD:$%SALES_PERIOD,%CRM_NAME!$AR:$AR,$C:$C,%CRM_NAME!$AS:$AS,$D:$D,%CRM_NAME!$AQ:$AQ,"%DOC_TYPE")')

SALES_METRES_WITHOUT_FIRST_COLUMN = FormulaTemplate('=SUMIFS(%CRM_ROW:%CRM_ROW,$%CRM_PERIOD:$%CRM_PERIOD,$%SALES_PERIOD:$%SALES_PERIOD,$%CRM_TYPE:$%CRM_TYPE,"%DOC_TYPE")+%SALES_CORRECTED:%SALES_CORRECTED')
SALES_METRES_WITHOUT_OTHER_COLUMN = FormulaTemplate('=SUMIFS(%CRM_ROW:%CRM_ROW,$%CRM_PERIOD:$%CRM_PERIOD,$%SALES_PERIOD:$%SALES_PERIOD,$%CRM_TYPE:$%CRM_TYPE,"%DOC_TYPE")+%SALES_CORRECTED:%SALES_CORRECTED+%PREV_COL:%PREV_COL')

SALES_MONEY_WITH_FIRST_COLUMN = FormulaTemplate('=SUMIFS(%CRM_ROW:%CRM_ROW,$%CRM_PERIOD:$%CRM_PERIOD,$%SALES_PERIOD:$%SALES_PERIOD,$%CRM_TYPE:$%CRM_TYPE,"Реализация_%DOC_TYPE")')
SALES_MONEY_WITH_OTHER_COLUMN = FormulaTemplate('=SUMIFS(%CRM_ROW:%CRM_ROW,$%CRM_PERIOD:$%CRM_PERIOD,$%SALES_PERIOD:$%SALES_PERIOD,$%CRM_TYPE:$%CRM_TYPE,"Реализация_%DOC_TYPE")+%PREV_COL:%PREV_COL')

CORRECTED_SALES = FormulaTemplate('=SUMIFS(%CRM_NAME!$BC:$BC,%CRM_NAME!$AM:$AM,$%SALES_PERIOD:$%SALES_PERIOD,%CRM_NAME!$AR:$AR,$C:$C,%CRM_NAME!$AS:$AS,$D:$D,%CRM_NAME!$AQ:$AQ,"%DOC_TYPE")')

SALES_MONEY_WITHOUT_FIRST_COLUMN = FormulaTemplate('=SUMIFS(%CRM_ROW:%CRM_ROW,$%CRM_PERIOD:$%CRM_PERIOD,$%SALES_PERIOD:$%SALES_PERIOD,$%CRM_TYPE:$%CRM_TYPE,"Реализация_%DOC_TYPE")+%SALES_CORRECTED:%SALES_CORRECTED')
SALES_MONEY_WITHOUT_OTHER_COLUMN = FormulaTemplate('=SUMIFS(%CRM_ROW:%CRM_ROW,$%CRM_PERIOD:$%CRM_PERIOD,$%SALES_PERIOD:$%SALES_PERIOD,$%CRM_TYPE:$%CRM_TYPE,"Реализация_%DOC_TYPE")+%SALES_CORRECTED:%SALES_CORRECTED+%PREV_COL:%PREV_COL')


PARTNER_SALES_METRES_FIRST_COLUMN = FormulaTemplate('=SUMIFS(%CRM_NAME!$AX:$AX,%CRM_NAME!$AT:$AT,"Да",%CRM_NAME!$AR:$AR,$C:$C,%CRM_NAME!$AS:$AS,$D:$D,%CRM_NAME!$AM:$AM,$%SALES_PERIOD:$%SALES_PERIOD,%CRM_NAME!$AV:$AV,"Да",%CRM_NAME!$AQ:$AQ,"%DOC_TYPE")'
                                       '+SUMIFS(%CRM_NAME!$BB:$BB,%CRM_NAME!$AT:$AT,"Да",%CRM_NAME!$AR:$AR,$C:$C,%CRM_NAME!$AS:$AS,$D:$D,%CRM_NAME!$AM:$AM,$%SALES_PERIOD:$%SALES_PERIOD,%CRM_NAME!$AV:$AV,"Да",%CRM_NAME!$AQ:$AQ,"%DOC_TYPE")')
PARTNER_SALES_METRES_OTHER_COLUMN = FormulaTemplate('=SUMIFS(%CRM_NAME!$AX:$AX,%CRM_NAME!$AT:$AT,"Да",%CRM_NAME!$AR:$AR,$C:$C,%CRM_NAME!$AS:$AS,$D:$D,%CRM_NAME!$AM:$AM,$%SALES_PERIOD:$%SALES_PERIOD,%CRM_NAME!$AV:$AV,"Да",%CRM_NAME!$AQ:$AQ,"%DOC_TYPE")'
                                       '+SUMIFS(%CRM_NAME!$BB:$BB,%CRM_NAME!$AT:$AT,"Да",%CRM_NAME!$AR:$AR,$C:$C,%CRM_NAME!$AS:$AS,$D:$D,%CRM_NAME!$AM:$AM,$%SALES_PERIOD:$%SALES_PERIOD,%CRM_NAME!$AV:$AV,"Да",%CRM_NAME!$AQ:$AQ,"%DOC_TYPE")+%PREV_COL:%PREV_COL')


PARTNER_SALES_MONEY_FIRST_COLUMN = FormulaTemplate('=SUMIFS(%CRM_NAME!$AY:$AY,%CRM_NAME!$AT:$AT,"Да",%CRM_NAME!$AR:$AR,$C:$C,%CRM_NAME!$AS:$AS,$D:$D,%CRM_NAME!$AM:$AM,$%SALES_PERIOD:$%SALES_PERIOD,%CRM_NAME!$AV:$AV,"Да",%CRM_NAME!$AQ:$AQ,"%DOC_TYPE")+'
                                                   'SUMIFS(%CRM_NAME!$BC:$BC,%CRM_NAME!$AT:$AT,"Да",%CRM_NAME!$AR:$AR,$C:$C,%CRM_NAME!$AS:$AS,$D:$D,%CRM_NAME!$AM:$AM,$%SALES_PERIOD:$%SALES_PERIOD,%CRM_NAME!$AV:$AV,"Да",%CRM_NAME!$AQ:$AQ,"%DOC_TYPE")')
PARTNER_SALES_MONEY_OTHER_COLUMN = FormulaTemplate('=SUMIFS(%CRM_NAME!$AY:$AY,%CRM_NAME!$AT:$AT,"Да",%CRM_NAME!$AR:$AR,$C:$C,%CRM_NAME!$AS:$AS,$D:$D,%CRM_NAME!$AM:$AM,$%SALES_PERIOD:$%SALES_PERIOD,%CRM_NAME!$AV:$AV,"Да",%CRM_NAME!$AQ:$AQ,"%DOC_TYPE")+'
                                                   'SUMIFS(%CRM_NAME!$BC:$BC,%CRM_NAME!$AT:$AT,"Да",%CRM_NAME!$AR:$AR,$C:$C,%CRM_NAME!$AS:$AS,$D:$D,%CRM_NAME!$AM:$AM,$%SALES_PERIOD:$%SALES_PERIOD,%CRM_NAME!$AV:$AV,"Да",%CRM_NAME!$AQ:$AQ,"%DOC_TYPE")+%PREV_COL:%PREV_COL')

FORMULA_METRES_CLOSE = FormulaTemplate('=SUMIFS(%CRM_NAME!$AY:$AY,%CRM_NAME!$AM:$AM,$%SALES_PERIOD:$%SALES_PERIOD,%CRM_NAME!$AR:$AR,$C:$C,%CRM_NAME!$AS:$AS,$D:$D,%CRM_NAME!$AQ:$AQ,"%DOC_TYPE")')
FORMULA_METRES_DENIAL = FormulaTemplate('=SUMIFS(%CRM_NAME!$AY:$AY,%CRM_NAME!$AP:$AP,$%SALES_PERIOD:$%SALES_PERIOD,%CRM_NAME!$AR:$AR,$C:$C,%CRM_NAME!$AS:$AS,$D:$D,%CRM_NAME!$AQ:$AQ,"%DOC_TYPE")')
FORMULA_MONEY_CLOSE = FormulaTemplate('=SUMIFS(%CRM_NAME!$AX:$AX,%CRM_NAME!$AM:$AM,$%SALES_PERIOD:$%SALES_PERIOD,%CRM_NAME!$AR:$AR,$C:$C,%CRM_NAME!$AS:$AS,$D:$D,%CRM_NAME!$AQ:$AQ,"%DOC_TYPE")')
FORMULA_MONEY_DENIAL = FormulaTemplate('=SUMIFS(%CRM_NAME!$AX:$AX,%CRM_NAME!$AP:$AP,$%SALES_PERIOD:$%SALES_PERIOD,%CRM_NAME!$AR:$AR,$C:$C,%CRM_NAME!$AS:$AS,$D:$D,%CRM_NAME!$AQ:$AQ,"%DOC_TYPE")')


