import string

class FormulaTemplate(string.Template):
    delimiter = '%'




SALES_METRES_WITH_FIRST_COLUMN = FormulaTemplate('=SUMIFS(%CRM_ROW:%CRM_ROW,$%CRM_PERIOD:$%CRM_PERIOD,$%SALES_PERIOD:$%SALES_PERIOD,$%CRM_TYPE:$%CRM_TYPE,"%DOC_TYPE")')
SALES_METRES_WITH_OTHER_COLUMN = FormulaTemplate('=SUMIFS(%CRM_ROW:%CRM_ROW,$%CRM_PERIOD:$%CRM_PERIOD,$%SALES_PERIOD:$%SALES_PERIOD,$%CRM_TYPE:$%CRM_TYPE,"%DOC_TYPE")+%PREV_COL:%PREV_COL')

CORRECTED_METRES = FormulaTemplate('=SUMIFS(%CRM_NAME!$BC:$BC,%CRM_NAME!$AN:$AN,$%SALES_PERIOD:$%SALES_PERIOD,%CRM_NAME!$AS:$AS,$C:$C,%CRM_NAME!$AT:$AT,$D:$D,%CRM_NAME!$AR:$AR,"%DOC_TYPE")')
SALES_METRES_WITHOUT_FIRST_COLUMN = FormulaTemplate('=SUMIFS(%CRM_ROW:%CRM_ROW,$%CRM_PERIOD:$%CRM_PERIOD,$%SALES_PERIOD:$%SALES_PERIOD,$%CRM_TYPE:$%CRM_TYPE,"%DOC_TYPE")+%SALES_CORRECTED:%SALES_CORRECTED')
SALES_METRES_WITHOUT_OTHER_COLUMN = FormulaTemplate('=SUMIFS(%CRM_ROW:%CRM_ROW,$%CRM_PERIOD:$%CRM_PERIOD,$%SALES_PERIOD:$%SALES_PERIOD,$%CRM_TYPE:$%CRM_TYPE,"%DOC_TYPE")+%SALES_CORRECTED:%SALES_CORRECTED+%PREV_COL:%PREV_COL')

SALES_MONEY_WITH_FIRST_COLUMN = FormulaTemplate('=SUMIFS(%CRM_ROW:%CRM_ROW,$%CRM_PERIOD:$%CRM_PERIOD,$%SALES_PERIOD:$%SALES_PERIOD,$%CRM_TYPE:$%CRM_TYPE,"Реализация_%DOC_TYPE")')
SALES_MONEY_WITH_OTHER_COLUMN = FormulaTemplate('=SUMIFS(%CRM_ROW:%CRM_ROW,$%CRM_PERIOD:$%CRM_PERIOD,$%SALES_PERIOD:$%SALES_PERIOD,$%CRM_TYPE:$%CRM_TYPE,"Реализация_%DOC_TYPE")+%PREV_COL:%PREV_COL')

CORRECTED_SALES = FormulaTemplate('=SUMIFS(%CRM_NAME!$BD:$BD,%CRM_NAME!$AN:$AN,$%SALES_PERIOD:$%SALES_PERIOD,%CRM_NAME!$AS:$AS,$C:$C,%CRM_NAME!$AT:$AT,$D:$D,%CRM_NAME!$AR:$AR,"%DOC_TYPE")')

SALES_MONEY_WITHOUT_FIRST_COLUMN = FormulaTemplate('=SUMIFS(%CRM_ROW:%CRM_ROW,$%CRM_PERIOD:$%CRM_PERIOD,$%SALES_PERIOD:$%SALES_PERIOD,$%CRM_TYPE:$%CRM_TYPE,"Реализация_%DOC_TYPE")+%SALES_CORRECTED:%SALES_CORRECTED')
SALES_MONEY_WITHOUT_OTHER_COLUMN = FormulaTemplate('=SUMIFS(%CRM_ROW:%CRM_ROW,$%CRM_PERIOD:$%CRM_PERIOD,$%SALES_PERIOD:$%SALES_PERIOD,$%CRM_TYPE:$%CRM_TYPE,"Реализация_%DOC_TYPE")+%SALES_CORRECTED:%SALES_CORRECTED+%PREV_COL:%PREV_COL')


PARTNER_SALES_METRES_FIRST_COLUMN = FormulaTemplate('=SUMIFS(%CRM_NAME!$AY:$AY,%CRM_NAME!$AU:$AU,"Да",%CRM_NAME!$AS:$AS,$C:$C,%CRM_NAME!$AT:$AT,$D:$D,%CRM_NAME!$AN:$AN,$%SALES_PERIOD:$%SALES_PERIOD,%CRM_NAME!$AW:$AW,"Да",%CRM_NAME!$AR:$AR,"%DOC_TYPE")'
                                       '+SUMIFS(%CRM_NAME!$BC:$BC,%CRM_NAME!$AU:$AU,"Да",%CRM_NAME!$AS:$AS,$C:$C,%CRM_NAME!$AT:$AT,$D:$D,%CRM_NAME!$AN:$AN,$%SALES_PERIOD:$%SALES_PERIOD,%CRM_NAME!$AW:$AW,"Да",%CRM_NAME!$AR:$AR,"%DOC_TYPE")')
PARTNER_SALES_METRES_OTHER_COLUMN = FormulaTemplate('=SUMIFS(%CRM_NAME!$AY:$AY,%CRM_NAME!$AU:$AU,"Да",%CRM_NAME!$AS:$AS,$C:$C,%CRM_NAME!$AT:$AT,$D:$D,%CRM_NAME!$AN:$AN,$%SALES_PERIOD:$%SALES_PERIOD,%CRM_NAME!$AW:$AW,"Да",%CRM_NAME!$AR:$AR,"%DOC_TYPE")'
                                       '+SUMIFS(%CRM_NAME!$BC:$BC,%CRM_NAME!$AU:$AU,"Да",%CRM_NAME!$AS:$AS,$C:$C,%CRM_NAME!$AT:$AT,$D:$D,%CRM_NAME!$AN:$AN,$%SALES_PERIOD:$%SALES_PERIOD,%CRM_NAME!$AW:$AW,"Да",%CRM_NAME!$AR:$AR,"%DOC_TYPE")+%PREV_COL:%PREV_COL')
# PARTNER_SALES_METRES_OTHER_COLUMN = FormulaTemplate('=SUMIFS(%CRM_NAME!$AX:$AX,%CRM_NAME!$AT:$AT,"Да",%CRM_NAME!$AR:$AR,$C:$C,%CRM_NAME!$AS:$AS,$D:$D,%CRM_NAME!$AM:$AM,$%SALES_PERIOD:$%SALES_PERIOD,%CRM_NAME!$AV:$AV,"Да",%CRM_NAME!$AQ:$AQ,"%DOC_TYPE")'
#                                        '+SUMIFS(%CRM_NAME!$BB:$BB,%CRM_NAME!$AT:$AT,"Да",%CRM_NAME!$AR:$AR,$C:$C,%CRM_NAME!$AS:$AS,$D:$D,%CRM_NAME!$AM:$AM,$%SALES_PERIOD:$%SALES_PERIOD,%CRM_NAME!$AV:$AV,"Да",%CRM_NAME!$AQ:$AQ,"%DOC_TYPE")+%PREV_COL:%PREV_COL')


PARTNER_SALES_MONEY_FIRST_COLUMN = FormulaTemplate('=SUMIFS(%CRM_NAME!$AZ:$AZ,%CRM_NAME!$AU:$AU,"Да",%CRM_NAME!$AS:$AS,$C:$C,%CRM_NAME!$AT:$AT,$D:$D,%CRM_NAME!$AN:$AN,$%SALES_PERIOD:$%SALES_PERIOD,%CRM_NAME!$AW:$AW,"Да",%CRM_NAME!$AR:$AR,"%DOC_TYPE")+'
                                                   'SUMIFS(%CRM_NAME!$BD:$BD,%CRM_NAME!$AU:$AU,"Да",%CRM_NAME!$AS:$AS,$C:$C,%CRM_NAME!$AT:$AT,$D:$D,%CRM_NAME!$AN:$AN,$%SALES_PERIOD:$%SALES_PERIOD,%CRM_NAME!$AW:$AW,"Да",%CRM_NAME!$AR:$AR,"%DOC_TYPE")')

PARTNER_SALES_MONEY_OTHER_COLUMN = FormulaTemplate('=SUMIFS(%CRM_NAME!$AZ:$AZ,%CRM_NAME!$AU:$AU,"Да",%CRM_NAME!$AS:$AS,$C:$C,%CRM_NAME!$AT:$AT,$D:$D,%CRM_NAME!$AN:$AN,$%SALES_PERIOD:$%SALES_PERIOD,%CRM_NAME!$AW:$AW,"Да",%CRM_NAME!$AR:$AR,"%DOC_TYPE")+'
                                                   'SUMIFS(%CRM_NAME!$BD:$BD,%CRM_NAME!$AU:$AU,"Да",%CRM_NAME!$AS:$AS,$C:$C,%CRM_NAME!$AT:$AT,$D:$D,%CRM_NAME!$AN:$AN,$%SALES_PERIOD:$%SALES_PERIOD,%CRM_NAME!$AW:$AW,"Да",%CRM_NAME!$AR:$AR,"%DOC_TYPE")+%PREV_COL:%PREV_COL')

# PARTNER_SALES_MONEY_OTHER_COLUMN = FormulaTemplate('=SUMIFS(%CRM_NAME!$AY:$AY,%CRM_NAME!$AT:$AT,"Да",%CRM_NAME!$AR:$AR,$C:$C,%CRM_NAME!$AS:$AS,$D:$D,%CRM_NAME!$AM:$AM,$%SALES_PERIOD:$%SALES_PERIOD,%CRM_NAME!$AV:$AV,"Да",%CRM_NAME!$AQ:$AQ,"%DOC_TYPE")+'
#                                                    'SUMIFS(%CRM_NAME!$BC:$BC,%CRM_NAME!$AT:$AT,"Да",%CRM_NAME!$AR:$AR,$C:$C,%CRM_NAME!$AS:$AS,$D:$D,%CRM_NAME!$AM:$AM,$%SALES_PERIOD:$%SALES_PERIOD,%CRM_NAME!$AV:$AV,"Да",%CRM_NAME!$AQ:$AQ,"%DOC_TYPE")+%PREV_COL:%PREV_COL')

FORMULA_METRES_CLOSE = FormulaTemplate('=SUMIFS(%CRM_NAME!$AY:$AY,%CRM_NAME!$AN:$AN,$%SALES_PERIOD:$%SALES_PERIOD,%CRM_NAME!$AS:$AS,$C:$C,%CRM_NAME!$AT:$AT,$D:$D,%CRM_NAME!$AR:$AR,"%DOC_TYPE")')
FORMULA_METRES_DENIAL = FormulaTemplate('=-SUMIFS(%CRM_NAME!$AY:$AY,%CRM_NAME!$AQ:$AQ,$%SALES_PERIOD:$%SALES_PERIOD,%CRM_NAME!$AS:$AS,$C:$C,%CRM_NAME!$AT:$AT,$D:$D,%CRM_NAME!$AR:$AR,"%DOC_TYPE")')
FORMULA_MONEY_CLOSE = FormulaTemplate('=SUMIFS(%CRM_NAME!$AZ:$AZ,%CRM_NAME!$AN:$AN,$%SALES_PERIOD:$%SALES_PERIOD,%CRM_NAME!$AS:$AS,$C:$C,%CRM_NAME!$AT:$AT,$D:$D,%CRM_NAME!$AR:$AR,"%DOC_TYPE")')
FORMULA_MONEY_DENIAL = FormulaTemplate('=-SUMIFS(%CRM_NAME!$AZ:$AZ,%CRM_NAME!$AQ:$AQ,$%SALES_PERIOD:$%SALES_PERIOD,%CRM_NAME!$AS:$AS,$C:$C,%CRM_NAME!$AT:$AT,$D:$D,%CRM_NAME!$AR:$AR,"%DOC_TYPE")')

PERIOD_FORMULA = FormulaTemplate(f'=IF(ISERROR(SEARCH("_",%COLUMN%ROW,1)),' \
        f'CONCATENATE(%COLUMN%ROW," год"),CONCATENATE(VLOOKUP(MID(%COLUMN%ROW,' \
        f'1,SEARCH("_",%COLUMN%ROW)-1)+0,%DICT_SHEET!$A:$B,2,0),"-е ",' \
        f'RIGHT(%COLUMN%ROW,4)," года"))')
